import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const cssPath = resolve(root, 'temp/styles.css')
const outPath = resolve(root, 'src/generated/styles.ts')

const css = readFileSync(cssPath, 'utf-8')

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(
  outPath,
  `// Auto-generated by scripts/embed-css.mjs — do not edit\nexport const styles = ${JSON.stringify(css)}\n`,
)

console.log(`Embedded ${(css.length / 1024).toFixed(1)}KB of CSS into src/generated/styles.ts`)
